import { expect, test } from '@playwright/test';

test('seeded dashboard supports ranking controls, dataset selection and details', async ({ page }) => {
  await page.goto('/?dataset=synthetic');
  await expect(page.getByRole('heading', { name: 'Activity ranking' })).toBeVisible();
  await expect(page.getByLabel('Team and season')).toHaveValue('synthetic');
  await expect(page.getByRole('table')).toContainText('Alex Example');
  await expect(page.getByRole('columnheader', { name: 'Home appearances' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Away appearances' })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Admin', exact: true })).toBeVisible();
  await expect(page.getByText('Training ↓').first()).toHaveAttribute('title', /Low declared training presence:/);
  await expect(page.getByRole('table')).not.toContainText('Casey Guest');
  await page.getByLabel('Show substitutes').check();
  await expect(page.getByRole('table')).toContainText('Casey Guest');
  await page.getByLabel('Ranking mode').selectOption('match');
  await page.getByLabel('Match source').selectOption('official');
  await expect(page.getByRole('columnheader', { name: 'Official score' })).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: 'Casey Guest' }).locator('.score')).toHaveText('50.0%');
  await page.getByLabel('Match source').selectOption('availability');
  await expect(page.getByRole('columnheader', { name: 'Availability score' })).toBeVisible();
  await page.getByLabel(/Training weight/).fill('70');
  await expect(page.getByRole('table')).toContainText('%');
  await page.getByRole('link', { name: 'Alex Example' }).click();
  await expect(page.getByRole('heading', { name: 'Alex Example' })).toBeVisible();
  await expect(page.getByText('Event history')).toBeVisible();
  await page.getByRole('link', { name: 'Matches' }).click();
  await page.getByRole('link', { name: /Compare players/ }).first().click();
  await expect(page.getByText('Available and officially played')).toBeVisible();
  await expect(page.getByText(/does not imply a selection decision/)).toBeVisible();
  await expect(page.locator('.grid')).not.toContainText('Casey Guest');
  await page.getByLabel('Show substitutes').check();
  await expect(page.locator('.grid')).toContainText('Casey Guest');
  await page.getByRole('link', { name: 'Monthly' }).click();
  await expect(page.getByLabel('Compare player')).not.toContainText('Casey Guest');
  await page.getByLabel('Show substitutes').check();
  await expect(page.getByLabel('Compare player')).toContainText('Casey Guest');
  await page.getByLabel('Compare player').selectOption({ label: 'Alex Example' });
  await expect(page.locator('.history .row').first()).toContainText('Alex Example');
  await expect(page.locator('.history .row').first()).toContainText('Declared training: 50.0%');
  await expect(page.locator('.history .row').first()).toContainText('Training: 100.0%');
  await expect(page.locator('.history .row').first()).not.toContainText('N/A%');
  await page.getByRole('link', { name: 'Training' }).click();
  await expect(page.getByRole('table')).not.toContainText('Casey Guest');
  await page.getByLabel('Show substitutes').check();
  await expect(page.getByRole('table')).toContainText('Casey Guest');
});
