import { readdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import type { DatasetConfig, EventType } from '../core/types.js';
import { readRoster } from '../core/roster.js';
import { normalizeName } from '../core/names.js';
import { openDatabase, now, issue, type AppDatabase } from './db.js';
import { ensurePlayer } from './identity.js';
import { readSportlinkPdf } from './sportlink.js';
import { TwizzitApi, type ApiEvent } from './twizzit-api.js';
import { TwizzitSiteClient } from './twizzit-client.js';

export interface IngestSummary { roster:{players:number}; sportlink:{imported:number;skipped:number;failed:number}; twizzit:{events:number;failed:number}; issues:number }
function beginImport(db:AppDatabase,id:string,source:string){return Number(db.prepare(`INSERT INTO imports(dataset_id,source,started_at,status) VALUES(?,?,?,'running')`).run(id,source,now()).lastInsertRowid)}
function finishImport(db:AppDatabase,id:number,status:string,summary:unknown){db.prepare(`UPDATE imports SET completed_at=?,status=?,summary=? WHERE id=?`).run(now(),status,JSON.stringify(summary),id)}
function classify(config:DatasetConfig,name:string|null|undefined):EventType|null {if(!name)return config.classification?.nullNameAsTraining?'training':null;const n=name.toLowerCase();if((config.classification?.trainingPatterns??['training']).some(p=>n.includes(p.toLowerCase())))return 'training';if((config.classification?.matchPatterns??[' - ','match','wedstrijd']).some(p=>n.includes(p.toLowerCase())))return 'match';return null}
function localDate(start:string){return start.slice(0,10)}

function ingestRoster(db:AppDatabase,config:DatasetConfig){const parsed=readRoster(config.rosterPath);const transaction=db.transaction(()=>{db.prepare(`UPDATE memberships SET kind='substitute' WHERE dataset_id=?`).run(config.id);for(const p of parsed.players)ensurePlayer(db,config.id,'roster',`${p.firstName} ${p.lastName}`,p.firstName,p.lastName,'core',p.role,p.shirtNumber,config.aliases);db.prepare(`UPDATE datasets SET last_roster_import=? WHERE id=?`).run(now(),config.id)});transaction();return parsed}

function ingestSportlink(db:AppDatabase,config:DatasetConfig,staff:Set<string>){const importId=beginImport(db,config.id,'sportlink');let imported=0,skipped=0,failed=0;db.prepare(`DELETE FROM quality_issues WHERE dataset_id=? AND source='sportlink'`).run(config.id);
  for(const filename of readdirSync(config.sportlinkPdfDirectory).filter(f=>f.toLowerCase().endsWith('.pdf')).sort()){const path=join(config.sportlinkPdfDirectory,filename);try{const {hash,match}=readSportlinkPdf(path,config.sportlink.teamName);if(db.prepare(`SELECT 1 FROM events WHERE dataset_id=? AND source_hash=? AND sportlink_scorable=1`).get(config.id,hash)){skipped++;continue}const tx=db.transaction(()=>{const old=db.prepare(`SELECT id FROM events WHERE dataset_id=? AND source_filename=?`).get(config.id,filename) as {id:number}|undefined;if(old)db.prepare(`DELETE FROM events WHERE id=?`).run(old.id);const existing=db.prepare(`SELECT id FROM events WHERE dataset_id=? AND local_date=? AND event_type='match' AND twizzit_id IS NOT NULL`).all(config.id,match.date) as Array<{id:number}>;let eventId:number;if(existing.length===1){eventId=existing[0].id;db.prepare(`UPDATE events SET side=?,opponent=?,sportlink_scorable=1,source_filename=?,source_hash=?,competition=?,score_home=?,score_away=? WHERE id=?`).run(match.side,match.opponent,filename,hash,match.competition,match.scoreHome,match.scoreAway,eventId)}else{const result=db.prepare(`INSERT INTO events(dataset_id,event_type,local_date,start_at,name,side,opponent,sportlink_scorable,source_filename,source_hash,competition,score_home,score_away) VALUES(?,'match',?,?,?,?,?,1,?,?,?,?,?)`).run(config.id,match.date,match.time?`${match.date}T${match.time}:00`:null,`${match.homeTeam} - ${match.awayTeam}`,match.side,match.opponent,filename,hash,match.competition,match.scoreHome,match.scoreAway);eventId=Number(result.lastInsertRowid);if(existing.length>1)issue(db,config.id,'matching','ambiguous_event','error',`Multiple Twizzit matches on ${match.date}`,filename)}for(const p of match.players){if(staff.has(normalizeName(p.name))){issue(db,config.id,'sportlink','staff_on_sheet','warning','Known staff entry ignored',filename);continue}const player=ensurePlayer(db,config.id,'sportlink',p.name,undefined,undefined,'substitute','Speler',p.shirtNumber,config.aliases);db.prepare(`INSERT OR REPLACE INTO appearances VALUES(?,?,?,?)`).run(eventId,player.id,p.shirtNumber,p.captain?1:0)}});tx();imported++}catch(e){failed++;issue(db,config.id,'sportlink','pdf_parse_failed','error',`PDF could not be imported: ${e instanceof Error?e.message:'unknown error'}`,filename)}}db.prepare(`UPDATE datasets SET last_sportlink_import=? WHERE id=?`).run(now(),config.id);finishImport(db,importId,failed?'incomplete':'complete',{imported,skipped,failed});return {imported,skipped,failed}}

async function ingestTwizzit(db:AppDatabase,config:DatasetConfig,staff:Set<string>){const apiUser=process.env.TWIZZIT_API_USERNAME,apiPassword=process.env.TWIZZIT_API_PASSWORD,siteUser=process.env.TWIZZIT_SITE_USERNAME,sitePassword=process.env.TWIZZIT_SITE_PASSWORD;if(!apiUser||!apiPassword||!siteUser||!sitePassword)throw new Error('All four Twizzit credentials are required');const importId=beginImport(db,config.id,'twizzit');const api=new TwizzitApi(apiUser,apiPassword);const discovery=await api.discover(config.twizzit.groupName,config.season,config.twizzit.organizationId);const all=await api.allEvents(discovery.organization.id,config.startDate,config.endDate);const events=all.filter(e=>e['event-groups']?.some(g=>g['group-id']===discovery.group.id)).map(e=>({source:e,type:classify(config,e.name)})).filter((e):e is {source:ApiEvent;type:EventType}=>e.type!==null);const site=new TwizzitSiteClient(siteUser,sitePassword);const loaded=[] as Array<{event:ApiEvent;type:EventType;details:Awaited<ReturnType<TwizzitSiteClient['activity']>>|null;error?:string}>;for(const event of events){try{loaded.push({event:event.source,type:event.type,details:await site.activity(String(event.source.id))})}catch(e){loaded.push({event:event.source,type:event.type,details:null,error:e instanceof Error?e.message:'unknown error'})}}
  let failed=loaded.filter(x=>!x.details).length;if(failed){const diagnose=db.transaction(()=>{db.prepare(`DELETE FROM quality_issues WHERE dataset_id=? AND source='twizzit'`).run(config.id);for(const item of loaded.filter(x=>!x.details))issue(db,config.id,'twizzit','event_scrape_failed','error',`Attendance could not be loaded; previous complete Twizzit state was preserved: ${item.error}`,String(item.event.id))});diagnose();finishImport(db,importId,'incomplete',{events:loaded.length,failed,preservedPreviousState:true});return {events:loaded.length,failed}}const tx=db.transaction(()=>{db.prepare(`DELETE FROM quality_issues WHERE dataset_id=? AND source IN ('twizzit','matching')`).run(config.id);db.prepare(`DELETE FROM attendance WHERE event_id IN (SELECT id FROM events WHERE dataset_id=?)`).run(config.id);db.prepare(`DELETE FROM events WHERE dataset_id=? AND twizzit_id IS NOT NULL AND sportlink_scorable=0`).run(config.id);db.prepare(`UPDATE events SET twizzit_id=NULL,twizzit_scorable=0 WHERE dataset_id=?`).run(config.id);
    for(const item of loaded){const e=item.event,date=localDate(e.start),eventName=e.name??`${config.twizzit.groupName} Training`;const groups=e['event-groups']??[];const our=groups.find(g=>g['group-id']===discovery.group.id);const other=groups.find(g=>g['group-id']!==discovery.group.id);const side=item.type==='match'?(our?.['is-home-team']?'home':'away'):null;let eventId:number;const sport=item.type==='match'?db.prepare(`SELECT id FROM events WHERE dataset_id=? AND local_date=? AND sportlink_scorable=1`).all(config.id,date) as Array<{id:number}>:[];if(sport.length===1){eventId=sport[0].id;db.prepare(`UPDATE events SET twizzit_id=?,twizzit_scorable=?,start_at=?,end_at=?,name=?,location=?,side=COALESCE(side,?),opponent=COALESCE(opponent,?) WHERE id=?`).run(String(e.id),item.details?1:0,e.start,e.end,eventName,e.address??null,side,other?.['group-name']??null,eventId)}else{eventId=Number(db.prepare(`INSERT INTO events(dataset_id,event_type,local_date,start_at,end_at,name,location,side,opponent,twizzit_id,twizzit_scorable) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(config.id,item.type,date,e.start,e.end,eventName,e.address??null,side,other?.['group-name']??null,String(e.id),item.details?1:0).lastInsertRowid);if(sport.length>1)issue(db,config.id,'matching','ambiguous_event','error',`Multiple Sportlink matches on ${date}`,String(e.id))}if(!item.details){issue(db,config.id,'twizzit','event_scrape_failed','error',`Attendance could not be loaded: ${item.error}`,String(e.id));continue}const attendanceById=new Map(item.details.attendances.map(a=>[a.contactId,a]));for(const c of item.details.contacts){if(staff.has(normalizeName(c.fullName)))continue;if(!c.functions.some(f=>/speler|gastspeler/i.test(f)))continue;const p=ensurePlayer(db,config.id,'twizzit',c.fullName,undefined,undefined,'substitute','Speler',null,config.aliases);const a=attendanceById.get(c.id);if(a&&!a.value){issue(db,config.id,'twizzit','unknown_attendance_value','error',`Unsupported attendance value for event ${e.id}`,String(e.id))}db.prepare(`INSERT OR REPLACE INTO attendance VALUES(?,?,?,?,?)`).run(eventId,p.id,a?.value??'unknown',a?.comment??null,a?.sourceValue??null)}}
    db.prepare(`UPDATE datasets SET last_twizzit_import=? WHERE id=?`).run(now(),config.id);for(const row of db.prepare(`SELECT id,local_date FROM events WHERE dataset_id=? AND event_type='match' AND twizzit_scorable=1 AND sportlink_scorable=0`).all(config.id) as Array<{id:number;local_date:string}>)issue(db,config.id,'matching','missing_sportlink','warning',`Twizzit match on ${row.local_date} has no Sportlink PDF`,String(row.id));for(const row of db.prepare(`SELECT id,local_date FROM events WHERE dataset_id=? AND event_type='match' AND sportlink_scorable=1 AND twizzit_scorable=0`).all(config.id) as Array<{id:number;local_date:string}>)issue(db,config.id,'matching','missing_twizzit','warning',`Sportlink match on ${row.local_date} has no Twizzit event`,String(row.id));for(const row of db.prepare(`SELECT p.id,p.first_name firstName,p.last_name lastName FROM players p JOIN memberships m ON m.player_id=p.id WHERE m.dataset_id=? AND m.kind='substitute'`).all(config.id) as Array<{id:number;firstName:string;lastName:string}>)issue(db,config.id,'matching','unmatched_player','warning',`Source identity is not in the core roster and is shown as a substitute: ${row.firstName} ${row.lastName}`,String(row.id));});tx();finishImport(db,importId,failed?'incomplete':'complete',{events:loaded.length,failed});return {events:loaded.length,failed}}

export async function ingest(config:DatasetConfig,options:{skipTwizzit?:boolean}={}){const db=openDatabase();db.prepare(`INSERT INTO datasets(id,display_name,season,start_date,end_date,timezone,config_path) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET display_name=excluded.display_name,season=excluded.season,start_date=excluded.start_date,end_date=excluded.end_date,timezone=excluded.timezone,config_path=excluded.config_path`).run(config.id,config.displayName,config.season,config.startDate,config.endDate,config.timezone,'config/datasets');const roster=ingestRoster(db,config),staff=new Set(roster.staffNames.map(normalizeName));const sportlink=ingestSportlink(db,config,staff);let twizzit:{events:number;failed:number};try{twizzit=options.skipTwizzit?{events:0,failed:0}:await ingestTwizzit(db,config,staff)}catch(e){issue(db,config.id,'twizzit','refresh_failed','error',`Twizzit refresh failed before replacement; previous complete state was preserved: ${e instanceof Error?e.message:'unknown error'}`);db.prepare(`UPDATE imports SET completed_at=?,status='incomplete',summary=? WHERE dataset_id=? AND source='twizzit' AND status='running'`).run(now(),JSON.stringify({preservedPreviousState:true}),config.id);db.close();throw e}const issues=(db.prepare(`SELECT count(*) n FROM quality_issues WHERE dataset_id=? AND resolved=0`).get(config.id) as {n:number}).n;db.close();return {roster:{players:roster.players.length},sportlink,twizzit,issues} satisfies IngestSummary}
