import { calculateMetrics, combinedScore } from '../core/scoring.js';
import { existsSync } from 'node:fs';
import { databasePath, openReadonlyDatabase as openDatabase } from './db.js';

export interface DatasetRow {id:string;displayName:string;season:string;startDate:string;endDate:string;timezone:string;lastRosterImport:string|null;lastSportlinkImport:string|null;lastTwizzitImport:string|null}
export function datasets():DatasetRow[]{if(!existsSync(databasePath()))return [];const db=openDatabase();const rows=db.prepare(`SELECT id,display_name displayName,season,start_date startDate,end_date endDate,timezone,last_roster_import lastRosterImport,last_sportlink_import lastSportlinkImport,last_twizzit_import lastTwizzitImport FROM datasets ORDER BY display_name,season`).all() as DatasetRow[];db.close();return rows}
export function selectedDataset(requested:string|null){const all=datasets();if(requested==='all')return {all,id:'all',isAll:true};return {all,id:all.some(d=>d.id===requested)?requested!:all[0]?.id??null,isAll:false}}
export function combinedRanking():any[]{return datasets().flatMap(d=>ranking(d.id).filter(r=>r.kind==='core').map(r=>({...r,teamId:d.id,teamName:d.displayName})))}
export function ranking(datasetId:string){const db=openDatabase();const players=db.prepare(`SELECT p.id,p.first_name firstName,p.last_name lastName,m.kind,m.shirt_number shirtNumber FROM players p JOIN memberships m ON m.player_id=p.id WHERE m.dataset_id=? ORDER BY p.last_name,p.first_name`).all(datasetId) as Array<{id:number;firstName:string;lastName:string;kind:string;shirtNumber:string|null}>;const events=db.prepare(`SELECT e.id,e.event_type type,e.side,e.twizzit_scorable twizzitScorable,e.sportlink_scorable sportlinkScorable,a.value attendance,CASE WHEN ap.player_id IS NULL THEN 0 ELSE 1 END appeared FROM events e LEFT JOIN attendance a ON a.event_id=e.id AND a.player_id=? LEFT JOIN appearances ap ON ap.event_id=e.id AND ap.player_id=? WHERE e.dataset_id=?`).all.bind(db.prepare(`SELECT e.id,e.event_type type,e.side,e.twizzit_scorable twizzitScorable,e.sportlink_scorable sportlinkScorable,a.value attendance,CASE WHEN ap.player_id IS NULL THEN 0 ELSE 1 END appeared FROM events e LEFT JOIN attendance a ON a.event_id=e.id AND a.player_id=? LEFT JOIN appearances ap ON ap.event_id=e.id AND ap.player_id=? WHERE e.dataset_id=?`));
  const rows=players.map(p=>{const facts=events(p.id,p.id,datasetId) as Parameters<typeof calculateMetrics>[0];const metrics=calculateMetrics(facts);const insights=[] as Array<{code:string,label:string,detail:string}>;if((metrics.training.percentage??100)<50)insights.push({code:'low-training',label:'Low training presence',detail:`${metrics.training.numerator}/${metrics.training.denominator}`});if((metrics.overallAdmin.percentage??100)<70)insights.push({code:'low-admin',label:'Low administration quality',detail:`${metrics.overallAdmin.numerator}/${metrics.overallAdmin.denominator}`});const mismatchYes=facts.filter(e=>e.type==='match'&&e.twizzitScorable&&e.sportlinkScorable&&e.attendance==='yes'&&!e.appeared).length;if(mismatchYes)insights.push({code:'available-not-played',label:'Available, not recorded as played',detail:`${mismatchYes} match${mismatchYes===1?'':'es'}`});const mismatchPlayed=facts.filter(e=>e.type==='match'&&e.twizzitScorable&&e.sportlinkScorable&&e.appeared&&e.attendance!=='yes').length;if(mismatchPlayed)insights.push({code:'played-not-yes',label:'Played with no/unknown declaration',detail:`${mismatchPlayed} match${mismatchPlayed===1?'':'es'}`});return {...p,metrics,combined:combinedScore(metrics.training,metrics.appearances),insights}});db.close();return rows}
export function eventHistory(datasetId:string,playerId:number):any[]{const db=openDatabase();const rows=db.prepare(`SELECT e.id,e.event_type type,e.local_date date,e.start_at startAt,e.name,e.location,e.side,e.opponent,e.twizzit_scorable twizzitScorable,e.sportlink_scorable sportlinkScorable,a.value attendance,a.comment,CASE WHEN ap.player_id IS NULL THEN 0 ELSE 1 END appeared FROM events e LEFT JOIN attendance a ON a.event_id=e.id AND a.player_id=? LEFT JOIN appearances ap ON ap.event_id=e.id AND ap.player_id=? WHERE e.dataset_id=? ORDER BY e.local_date,e.start_at`).all(playerId,playerId,datasetId) as any[];db.close();return rows}
export function player(datasetId:string,id:number):any{const rows=ranking(datasetId);const summary=rows.find(p=>p.id===id);return summary?{summary,history:eventHistory(datasetId,id)}:null}
export function matches(datasetId:string):any[]{const db=openDatabase();const rows=db.prepare(`SELECT id,local_date date,start_at startAt,name,side,opponent,twizzit_scorable twizzitScorable,sportlink_scorable sportlinkScorable,score_home scoreHome,score_away scoreAway FROM events WHERE dataset_id=? AND event_type='match' ORDER BY local_date`).all(datasetId) as any[];db.close();return rows}
export function matchDetail(datasetId:string,id:number):any{const db=openDatabase();const match=db.prepare(`SELECT id,local_date date,start_at startAt,name,side,opponent,twizzit_scorable twizzitScorable,sportlink_scorable sportlinkScorable FROM events WHERE dataset_id=? AND id=? AND event_type='match'`).get(datasetId,id) as any;if(!match){db.close();return null}const players=db.prepare(`SELECT p.id,p.first_name firstName,p.last_name lastName,m.kind,a.value attendance,a.comment,CASE WHEN ap.player_id IS NULL THEN 0 ELSE 1 END appeared FROM players p JOIN memberships m ON m.player_id=p.id LEFT JOIN attendance a ON a.player_id=p.id AND a.event_id=? LEFT JOIN appearances ap ON ap.player_id=p.id AND ap.event_id=? WHERE m.dataset_id=? ORDER BY p.last_name,p.first_name`).all(id,id,datasetId) as Array<any>;const groups={availablePlayed:[],availableNotPlayed:[],playedNo:[],playedUnknown:[],notPlayed:[]} as Record<string,any[]>;for(const p of players){if(p.attendance==='yes'&&p.appeared)groups.availablePlayed.push(p);else if(p.attendance==='yes')groups.availableNotPlayed.push(p);else if(p.attendance==='no'&&p.appeared)groups.playedNo.push(p);else if(p.appeared)groups.playedUnknown.push(p);else groups.notPlayed.push(p)}db.close();return {match,groups}}
export function trainings(datasetId:string):any[]{const db=openDatabase();const events=db.prepare(`SELECT id,local_date date,start_at startAt,name,location,twizzit_scorable twizzitScorable FROM events WHERE dataset_id=? AND event_type='training' ORDER BY local_date`).all(datasetId) as Array<any>;const rows=events.map(e=>({...e,responses:db.prepare(`SELECT p.id,p.first_name firstName,p.last_name lastName,m.kind,COALESCE(a.value,'unknown') value,a.comment FROM players p JOIN memberships m ON m.player_id=p.id LEFT JOIN attendance a ON a.player_id=p.id AND a.event_id=? WHERE m.dataset_id=? ORDER BY p.last_name,p.first_name`).all(e.id,datasetId) as any[]}));db.close();return rows}
export function quality(datasetId:string):any[]{const db=openDatabase();const rows=db.prepare(`SELECT id,source,code,severity,message,source_ref sourceRef,created_at createdAt FROM quality_issues WHERE dataset_id=? AND resolved=0 ORDER BY CASE severity WHEN 'error' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,created_at DESC`).all(datasetId) as any[];db.close();return rows}
export function monthly(datasetId:string){
  const ranks=ranking(datasetId);
  const all=ranks.map(player=>({player,history:eventHistory(datasetId,player.id)}));
  const months=[...new Set(all.flatMap(entry=>(entry.history as Array<{date:string}>).map(event=>event.date.slice(0,7))))].sort();
  return {
    players:ranks.map(player=>({id:player.id,name:`${player.firstName} ${player.lastName}`,kind:player.kind})),
    months:months.map(month=>{
      const histories=all.map(entry=>({playerId:entry.player.id,kind:entry.player.kind,metrics:calculateMetrics((entry.history as Array<any>).filter(event=>event.date.startsWith(month)).map(event=>({type:event.type,side:event.side,twizzitScorable:Boolean(event.twizzitScorable),sportlinkScorable:Boolean(event.sportlinkScorable),attendance:event.attendance??'unknown',appeared:Boolean(event.appeared)})))}));
      const core=histories.filter(entry=>entry.kind==='core');
      const avg=(key:'training'|'availability'|'appearances')=>{const values=core.map(entry=>entry.metrics[key].percentage).filter((value):value is number=>value!==null);return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length*10)/10:null};
      return {month,team:{training:avg('training'),availability:avg('availability'),appearances:avg('appearances')},players:histories};
    })
  };
}
